version: 2
jobs:
  lint:
    docker:
      - image: cimg/go:1.18.1
    working_directory: /go/src/github.com/yoheimuta/go-protoparser
    steps:
      - checkout
      - run: make dev/install/dep
      - run: make test/lint
  test:
    docker:
      - image: cimg/go:1.18.1
    working_directory: /go/src/github.com/yoheimuta/go-protoparser
    steps:
      - checkout
      - run: make test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
