# Runs lint and tests on master and feature branches.
name: Lint and test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dev deps
        run: make dev/install/dep
      - name: Lint
        run: make test/lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
